### ISSUE TITLE
Request me to sign in google account, no captha?

### ISSUE THREAD

**Issue by ab-glow** [ItsFuego/Captcha-Solver#3]
When I run it request me to sign in to my google account but after I signed in it says I should use another browser and the program doesn't go further than that. I did try out to sign out on my google chrome browser before as mentioned in your read me document. 

But again I tried to run it and it didn't show me captchas at all only requesting me to sign in to my Google account, I don't know what to do next.

**Comment by NoahCardoza** [comment]
That's because Google now tries to block users from signing in from Electron. It might be useful to checkout this [CaptchaHarvester](https://github.com/NoahCardoza/CaptchaHarvester) which utilizes your already installed chrome browser.

**Comment by ab-glow** [comment]
Will check out the repository.
